Fix: add totalNoOfTransactions to summary response
kaeruB/suzuchi-ginkou-server pull request #3
Opened 2023-02-19 00:08 UTC by kaeruB

Fix: add totalNoOfTransactions to summary response so the load more button can be implemented properly.

2023-02-19 03:39 UTC, kazoogon requested changes

2023-02-19 03:39 UTC, kazoogon commented on src/controllers/transactionController.ts
> +        totalNoOfTransactions,
`NoOf` 
気になるw
https://github.com/kaeruB/suzuchi-ginkou-client/pull/19#discussion_r1111143032

2023-02-19 03:39 UTC, kazoogon commented on src/controllers/transactionController.ts
>      const usersIdsInPair = retrieveUsersIdsFromPairId(pairId)
`retrieveUsersIdsFromPairId`
ten variable latwo rozumiec desu.
chociaz ogolnie daje `by` zamiast `from`

`retrieveUsersIdsByPairId`

2023-02-19 03:39 UTC, kazoogon commented on src/controllers/transactionController.ts
> -      Number.parseInt(req.query.historyListLength as string) : 5
dobrze usnelas `5` desu.
ogolnie taki number nazywa sie `magic number` desu, powinno zrozumiec jesli nie znasz desu

2023-02-19 03:39 UTC, kazoogon commented on src/controllers/transactionController.ts
>      const usersDetails = await retrieveUsersDetails(usersIdsInPair)
`usersIdsInPair`
↓
`userIdsInPair`

dame?

2023-02-26 00:32 UTC, kaeruB commented on src/controllers/transactionController.ts
>      const usersIdsInPair = retrieveUsersIdsFromPairId(pairId)
いいね〜 😃

2023-02-26 00:33 UTC, kaeruB commented on src/controllers/transactionController.ts
> -      Number.parseInt(req.query.historyListLength as string) : 5
知ってます〜

2023-02-26 00:35 UTC, kaeruB commented on src/controllers/transactionController.ts
>      const usersDetails = await retrieveUsersDetails(usersIdsInPair)
確かに 🤔

2023-02-26 02:07 UTC, kaeruB commented on src/controllers/transactionController.ts
>      const usersIdsInPair = retrieveUsersIdsFromPairId(pairId)
`decodePairUserIds`　どうですか？こちの方がやってることを伝わるかも〜

2023-02-26 08:28 UTC, kazoogon commented on src/controllers/transactionController.ts
>      const usersIdsInPair = retrieveUsersIdsFromPairId(pairId)
`retrieveUsersIdsByPairId` → `decodePairUserIds` ?

2023-02-26 08:33 UTC, kazoogon requested changes

2023-02-26 08:33 UTC, kazoogon commented on src/controllers/transactionController.ts
> +import {groupMoneyByUserInPair, decodePairUserIds} from "../utils/functions/commons";
`decodePairUserIds` czyli convert PairUserIds ? ale jak?

2023-02-26 08:33 UTC, kazoogon commented on src/controllers/transactionController.ts
> +    const pairUserIds = decodePairUserIds(pairId)
`pairUserIds` kore lepsze niz `usersIdsInPair` desuna

2023-03-05 03:42 UTC, kazoogon approved these changes

2023-03-05 03:57 UTC, merged